"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """$username$hostname$os[](#3c4161)$directory[](fg:#3c4161 bg:#1f2030)$git_branch$git_status$python$fill$line_break$character"""

[os]
disabled = false
format = "[$symbol](bg:#1f2030 fg:#blue)"

[os.symbols]
Ubuntu  = "󰕈"
Artix   = "󰣇"
Arch    = "󰣇"
CachyOS = "󰣇"
Macos   = ""

[directory]
style		  = "bg:#3c4161 fg:#83aafe"
read_only_style	  = "bg:#3c4161 fg:#e100aa"
format            = "[$path]($style)[$read_only]($read_only_style)"
truncation_length = 4
truncate_to_repo  = true

[git_branch]
symbol = ""
style  = "bg:#1f2030 fg:bold purple"
format = "[ $symbol $branch ]($style)"

[git_status]
style      = "bg:#1f2030 fg:#83aafe"
format     = "($ahead_behind$staged$modified$untracked$deleted$conflicted)"
ahead      = "[⇡$count ](bg:#1f2030 fg:bold cyan)"
behind     = "[⇣$count ](bg:#1f2030 fg:bold cyan)"
diverged   = "[⇡$ahead_count⇣$behind_count ](bg:#1f2030 fg:bold cyan)"
staged     = "[+$count ](bg:#1f2030 fg:bold green)"
modified   = "[●$count ](bg:#1f2030 fg:bold yellow)"
untracked  = "[?$count ](bg:#1f2030 fg:bold white)"
deleted    = "[✘$count ](bg:#1f2030 fg:bold red)"
conflicted = "[⚡$count ](bg:#1f2030 fg:bold red)"

[fill]
symbol = ' '
style = "bg:#1f2030"

[hostname]
ssh_only = true
ssh_symbol = "🌐"
trim_at = "."
detect_env_vars = []
format = "[$ssh_symbol$hostname]($style) "
style = "bg:#1f2030 fg:green dimmed bold"
disabled = false

[hostname.aliases]

[username]
detect_env_vars = []
format = "[$user]($style)"
style_root = "bg:#1f2030 fg:red bold"
style_user = "bg:#ff2030 fg:yellow bold"
show_always = false
disabled = false

[username.aliases]
"mjodom" = ""

[line_break]
disabled = false

[python]
#symbol = ""
#format = "[$symbol$version](green) "
format = "[${symbol}${version} (\\($virtualenv\\))]($style) "
style = "bold green"

[nodejs]
symbol = ""
format = "[$symbol $version](green) "

[rust]
symbol = ""
format = "[$symbol $version](red) "

[golang]
symbol = ""
format = "[$symbol $version](cyan) "

[php]
symbol = ""
format = "[$symbol $version](purple) "

[character]
success_symbol = "[└─>](green)"
error_symbol   = "[└─>](red)"
vimcmd_symbol  = "[└─<](blue)"
